### ISSUE TITLE
Error extracting Token from client

### ISSUE THREAD

**Issue by londarks** [sokripon/TribesCheat#1]
When starting the script and leaving the token empty, in the program it tries to find the client's token, but it responds with this error:
```
2022-09-24 15:59:11.044 | INFO     | __main__:<module>:463 - No auth token provided, trying to get it from the game memory(make sure that the game is running!)

line 465, in <module>
ticket = TribeClient.get_ticket_from_game_memory()


line 15, in follow_offsets
 val = pointer + offset
 
 
raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 29
```

Would there be any solution for this?
ps: Yes the game was open

**Comment by sokripon** [comment]
The latest big update most likely changed a lot in tom, so the offsets are wrong.
Giving horns still works if you are able to get the auth token yourself (you can use fiddler (classic) for that The request with the url `https://api.tribesofmidgard.com/live/users/auth/steam` gives you the token in the response 
![Fiddler_QgBIhdNEny](https://user-images.githubusercontent.com/79755465/192130429-69fe8132-15a7-4652-9503-389b756d463e.png)
).
Giving xp seems to need a complete rework, cause the xp "calculation" changed in the latest update.

I will fix the issues in the following week.

**Comment by londarks** [comment]
I managed to get my access token, thank you very much for the tip, I will contribute to the project as soon as you update the data next week.

**Comment by sokripon** [comment]
@londarks Updated, everything should work now. 👍
